# Generated by Django 3.1.2 on 2020-11-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barba', models.CharField(choices=[('Com Barba', 'Com Barba'), ('Sem Barba', 'Sem Barba')], max_length=10, verbose_name='Barba')),
            ],
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_corte', models.CharField(choices=[('Social', 'Social'), ('Degradê', 'Degradê')], max_length=10, verbose_name='Cortes')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('José', 'José'), ('Pedro', 'Pedro'), ('PH', 'PH')], max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbeariaApp.barba')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbeariaApp.funcionario')),
                ('tipo_de_corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbeariaApp.corte')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviço',
            },
        ),
    ]
