# Generated by Django 3.1.2 on 2020-11-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbeariaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
    ]
